[phases.setup]
nixPkgs = ["php", "php81Extensions.pdo_mysql", "php81Extensions.fileinfo"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate --force",
  "php artisan migrate --force"  # ðŸ‘ˆ ejecuta las migraciones automÃ¡ticamente
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
